apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-hello-world
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-hello-world
    spec:
      containers:
        - image: hello-world:latest
          name: hello-world
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"