apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tag-core
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/tag-core/tag-core
    repoURL: 'https://github.com/craigg-wex/ps-wex-k8s.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
